// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CreatePlayer.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CreatePlayer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* CreatePlayer_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CreatePlayer_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CreatePlayer_2eproto() {
  protobuf_AddDesc_CreatePlayer_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CreatePlayer.proto");
  GOOGLE_CHECK(file != NULL);
  CreatePlayer_descriptor_ = file->message_type(0);
  static const int CreatePlayer_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreatePlayer, player_),
  };
  CreatePlayer_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CreatePlayer_descriptor_,
      CreatePlayer::default_instance_,
      CreatePlayer_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreatePlayer, _has_bits_[0]),
      -1,
      -1,
      sizeof(CreatePlayer),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreatePlayer, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CreatePlayer_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CreatePlayer_descriptor_, &CreatePlayer::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CreatePlayer_2eproto() {
  delete CreatePlayer::default_instance_;
  delete CreatePlayer_reflection_;
}

void protobuf_AddDesc_CreatePlayer_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022CreatePlayer.proto\"\036\n\014CreatePlayer\022\016\n\006"
    "Player\030\001 \002(\t", 52);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CreatePlayer.proto", &protobuf_RegisterTypes);
  CreatePlayer::default_instance_ = new CreatePlayer();
  CreatePlayer::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CreatePlayer_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CreatePlayer_2eproto {
  StaticDescriptorInitializer_CreatePlayer_2eproto() {
    protobuf_AddDesc_CreatePlayer_2eproto();
  }
} static_descriptor_initializer_CreatePlayer_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int CreatePlayer::kPlayerFieldNumber;
#endif  // !_MSC_VER

CreatePlayer::CreatePlayer()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CreatePlayer)
}

void CreatePlayer::InitAsDefaultInstance() {
}

CreatePlayer::CreatePlayer(const CreatePlayer& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CreatePlayer)
}

void CreatePlayer::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  player_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CreatePlayer::~CreatePlayer() {
  // @@protoc_insertion_point(destructor:CreatePlayer)
  SharedDtor();
}

void CreatePlayer::SharedDtor() {
  player_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void CreatePlayer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CreatePlayer::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CreatePlayer_descriptor_;
}

const CreatePlayer& CreatePlayer::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CreatePlayer_2eproto();
  return *default_instance_;
}

CreatePlayer* CreatePlayer::default_instance_ = NULL;

CreatePlayer* CreatePlayer::New(::google::protobuf::Arena* arena) const {
  CreatePlayer* n = new CreatePlayer;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CreatePlayer::Clear() {
  if (has_player()) {
    player_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool CreatePlayer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CreatePlayer)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string Player = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_player()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->player().data(), this->player().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "CreatePlayer.Player");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CreatePlayer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CreatePlayer)
  return false;
#undef DO_
}

void CreatePlayer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CreatePlayer)
  // required string Player = 1;
  if (has_player()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->player().data(), this->player().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "CreatePlayer.Player");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->player(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CreatePlayer)
}

::google::protobuf::uint8* CreatePlayer::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CreatePlayer)
  // required string Player = 1;
  if (has_player()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->player().data(), this->player().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "CreatePlayer.Player");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->player(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CreatePlayer)
  return target;
}

int CreatePlayer::ByteSize() const {
  int total_size = 0;

  // required string Player = 1;
  if (has_player()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->player());
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CreatePlayer::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CreatePlayer* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CreatePlayer*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CreatePlayer::MergeFrom(const CreatePlayer& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_player()) {
      set_has_player();
      player_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.player_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void CreatePlayer::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CreatePlayer::CopyFrom(const CreatePlayer& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreatePlayer::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void CreatePlayer::Swap(CreatePlayer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CreatePlayer::InternalSwap(CreatePlayer* other) {
  player_.Swap(&other->player_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CreatePlayer::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CreatePlayer_descriptor_;
  metadata.reflection = CreatePlayer_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
