// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CreatePlayer.proto

#ifndef PROTOBUF_CreatePlayer_2eproto__INCLUDED
#define PROTOBUF_CreatePlayer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_CreatePlayer_2eproto();
void protobuf_AssignDesc_CreatePlayer_2eproto();
void protobuf_ShutdownFile_CreatePlayer_2eproto();

class CreatePlayer;

// ===================================================================

class CreatePlayer : public ::google::protobuf::Message {
 public:
  CreatePlayer();
  virtual ~CreatePlayer();

  CreatePlayer(const CreatePlayer& from);

  inline CreatePlayer& operator=(const CreatePlayer& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreatePlayer& default_instance();

  void Swap(CreatePlayer* other);

  // implements Message ----------------------------------------------

  inline CreatePlayer* New() const { return New(NULL); }

  CreatePlayer* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CreatePlayer& from);
  void MergeFrom(const CreatePlayer& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CreatePlayer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string Player = 1;
  inline bool has_player() const;
  inline void clear_player();
  static const int kPlayerFieldNumber = 1;
  inline const ::std::string& player() const;
  inline void set_player(const ::std::string& value);
  inline void set_player(const char* value);
  inline void set_player(const char* value, size_t size);
  inline ::std::string* mutable_player();
  inline ::std::string* release_player();
  inline void set_allocated_player(::std::string* player);

  // @@protoc_insertion_point(class_scope:CreatePlayer)
 private:
  inline void set_has_player();
  inline void clear_has_player();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr player_;
  friend void  protobuf_AddDesc_CreatePlayer_2eproto();
  friend void protobuf_AssignDesc_CreatePlayer_2eproto();
  friend void protobuf_ShutdownFile_CreatePlayer_2eproto();

  void InitAsDefaultInstance();
  static CreatePlayer* default_instance_;
};
// ===================================================================


// ===================================================================

// CreatePlayer

// required string Player = 1;
inline bool CreatePlayer::has_player() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CreatePlayer::set_has_player() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CreatePlayer::clear_has_player() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CreatePlayer::clear_player() {
  player_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_player();
}
inline const ::std::string& CreatePlayer::player() const {
  // @@protoc_insertion_point(field_get:CreatePlayer.Player)
  return player_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreatePlayer::set_player(const ::std::string& value) {
  set_has_player();
  player_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CreatePlayer.Player)
}
inline void CreatePlayer::set_player(const char* value) {
  set_has_player();
  player_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CreatePlayer.Player)
}
inline void CreatePlayer::set_player(const char* value, size_t size) {
  set_has_player();
  player_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CreatePlayer.Player)
}
inline ::std::string* CreatePlayer::mutable_player() {
  set_has_player();
  // @@protoc_insertion_point(field_mutable:CreatePlayer.Player)
  return player_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreatePlayer::release_player() {
  clear_has_player();
  return player_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreatePlayer::set_allocated_player(::std::string* player) {
  if (player != NULL) {
    set_has_player();
  } else {
    clear_has_player();
  }
  player_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), player);
  // @@protoc_insertion_point(field_set_allocated:CreatePlayer.Player)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CreatePlayer_2eproto__INCLUDED
