// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Pause.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Pause.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Pause_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Pause_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Pause_2eproto() {
  protobuf_AddDesc_Pause_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Pause.proto");
  GOOGLE_CHECK(file != NULL);
  Pause_descriptor_ = file->message_type(0);
  static const int Pause_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pause, numofplayers_),
  };
  Pause_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Pause_descriptor_,
      Pause::default_instance_,
      Pause_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pause, _has_bits_[0]),
      -1,
      -1,
      sizeof(Pause),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pause, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Pause_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Pause_descriptor_, &Pause::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Pause_2eproto() {
  delete Pause::default_instance_;
  delete Pause_reflection_;
}

void protobuf_AddDesc_Pause_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013Pause.proto\"\035\n\005Pause\022\024\n\014NumOfPlayers\030\001"
    " \002(\005", 44);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Pause.proto", &protobuf_RegisterTypes);
  Pause::default_instance_ = new Pause();
  Pause::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Pause_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Pause_2eproto {
  StaticDescriptorInitializer_Pause_2eproto() {
    protobuf_AddDesc_Pause_2eproto();
  }
} static_descriptor_initializer_Pause_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int Pause::kNumOfPlayersFieldNumber;
#endif  // !_MSC_VER

Pause::Pause()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Pause)
}

void Pause::InitAsDefaultInstance() {
}

Pause::Pause(const Pause& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Pause)
}

void Pause::SharedCtor() {
  _cached_size_ = 0;
  numofplayers_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Pause::~Pause() {
  // @@protoc_insertion_point(destructor:Pause)
  SharedDtor();
}

void Pause::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Pause::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Pause::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Pause_descriptor_;
}

const Pause& Pause::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Pause_2eproto();
  return *default_instance_;
}

Pause* Pause::default_instance_ = NULL;

Pause* Pause::New(::google::protobuf::Arena* arena) const {
  Pause* n = new Pause;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Pause::Clear() {
  numofplayers_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Pause::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Pause)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 NumOfPlayers = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &numofplayers_)));
          set_has_numofplayers();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Pause)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Pause)
  return false;
#undef DO_
}

void Pause::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Pause)
  // required int32 NumOfPlayers = 1;
  if (has_numofplayers()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->numofplayers(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Pause)
}

::google::protobuf::uint8* Pause::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Pause)
  // required int32 NumOfPlayers = 1;
  if (has_numofplayers()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->numofplayers(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Pause)
  return target;
}

int Pause::ByteSize() const {
  int total_size = 0;

  // required int32 NumOfPlayers = 1;
  if (has_numofplayers()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->numofplayers());
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Pause::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Pause* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Pause*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Pause::MergeFrom(const Pause& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_numofplayers()) {
      set_numofplayers(from.numofplayers());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Pause::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Pause::CopyFrom(const Pause& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Pause::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Pause::Swap(Pause* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Pause::InternalSwap(Pause* other) {
  std::swap(numofplayers_, other->numofplayers_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Pause::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Pause_descriptor_;
  metadata.reflection = Pause_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
