// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Pause.proto

#ifndef PROTOBUF_Pause_2eproto__INCLUDED
#define PROTOBUF_Pause_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Pause_2eproto();
void protobuf_AssignDesc_Pause_2eproto();
void protobuf_ShutdownFile_Pause_2eproto();

class Pause;

// ===================================================================

class Pause : public ::google::protobuf::Message {
 public:
  Pause();
  virtual ~Pause();

  Pause(const Pause& from);

  inline Pause& operator=(const Pause& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Pause& default_instance();

  void Swap(Pause* other);

  // implements Message ----------------------------------------------

  inline Pause* New() const { return New(NULL); }

  Pause* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Pause& from);
  void MergeFrom(const Pause& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Pause* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 NumOfPlayers = 1;
  inline bool has_numofplayers() const;
  inline void clear_numofplayers();
  static const int kNumOfPlayersFieldNumber = 1;
  inline ::google::protobuf::int32 numofplayers() const;
  inline void set_numofplayers(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Pause)
 private:
  inline void set_has_numofplayers();
  inline void clear_has_numofplayers();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 numofplayers_;
  friend void  protobuf_AddDesc_Pause_2eproto();
  friend void protobuf_AssignDesc_Pause_2eproto();
  friend void protobuf_ShutdownFile_Pause_2eproto();

  void InitAsDefaultInstance();
  static Pause* default_instance_;
};
// ===================================================================


// ===================================================================

// Pause

// required int32 NumOfPlayers = 1;
inline bool Pause::has_numofplayers() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Pause::set_has_numofplayers() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Pause::clear_has_numofplayers() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Pause::clear_numofplayers() {
  numofplayers_ = 0;
  clear_has_numofplayers();
}
inline ::google::protobuf::int32 Pause::numofplayers() const {
  // @@protoc_insertion_point(field_get:Pause.NumOfPlayers)
  return numofplayers_;
}
inline void Pause::set_numofplayers(::google::protobuf::int32 value) {
  set_has_numofplayers();
  numofplayers_ = value;
  // @@protoc_insertion_point(field_set:Pause.NumOfPlayers)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Pause_2eproto__INCLUDED
