// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PauseOtherPlayers.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PauseOtherPlayers.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PauseOtherPlayers_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PauseOtherPlayers_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_PauseOtherPlayers_2eproto() {
  protobuf_AddDesc_PauseOtherPlayers_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "PauseOtherPlayers.proto");
  GOOGLE_CHECK(file != NULL);
  PauseOtherPlayers_descriptor_ = file->message_type(0);
  static const int PauseOtherPlayers_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PauseOtherPlayers, paused_),
  };
  PauseOtherPlayers_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PauseOtherPlayers_descriptor_,
      PauseOtherPlayers::default_instance_,
      PauseOtherPlayers_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PauseOtherPlayers, _has_bits_[0]),
      -1,
      -1,
      sizeof(PauseOtherPlayers),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PauseOtherPlayers, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_PauseOtherPlayers_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PauseOtherPlayers_descriptor_, &PauseOtherPlayers::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_PauseOtherPlayers_2eproto() {
  delete PauseOtherPlayers::default_instance_;
  delete PauseOtherPlayers_reflection_;
}

void protobuf_AddDesc_PauseOtherPlayers_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027PauseOtherPlayers.proto\"#\n\021PauseOtherP"
    "layers\022\016\n\006paused\030\001 \002(\010", 62);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PauseOtherPlayers.proto", &protobuf_RegisterTypes);
  PauseOtherPlayers::default_instance_ = new PauseOtherPlayers();
  PauseOtherPlayers::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PauseOtherPlayers_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PauseOtherPlayers_2eproto {
  StaticDescriptorInitializer_PauseOtherPlayers_2eproto() {
    protobuf_AddDesc_PauseOtherPlayers_2eproto();
  }
} static_descriptor_initializer_PauseOtherPlayers_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int PauseOtherPlayers::kPausedFieldNumber;
#endif  // !_MSC_VER

PauseOtherPlayers::PauseOtherPlayers()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PauseOtherPlayers)
}

void PauseOtherPlayers::InitAsDefaultInstance() {
}

PauseOtherPlayers::PauseOtherPlayers(const PauseOtherPlayers& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PauseOtherPlayers)
}

void PauseOtherPlayers::SharedCtor() {
  _cached_size_ = 0;
  paused_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PauseOtherPlayers::~PauseOtherPlayers() {
  // @@protoc_insertion_point(destructor:PauseOtherPlayers)
  SharedDtor();
}

void PauseOtherPlayers::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PauseOtherPlayers::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PauseOtherPlayers::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PauseOtherPlayers_descriptor_;
}

const PauseOtherPlayers& PauseOtherPlayers::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PauseOtherPlayers_2eproto();
  return *default_instance_;
}

PauseOtherPlayers* PauseOtherPlayers::default_instance_ = NULL;

PauseOtherPlayers* PauseOtherPlayers::New(::google::protobuf::Arena* arena) const {
  PauseOtherPlayers* n = new PauseOtherPlayers;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PauseOtherPlayers::Clear() {
  paused_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool PauseOtherPlayers::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PauseOtherPlayers)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool paused = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &paused_)));
          set_has_paused();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PauseOtherPlayers)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PauseOtherPlayers)
  return false;
#undef DO_
}

void PauseOtherPlayers::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PauseOtherPlayers)
  // required bool paused = 1;
  if (has_paused()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->paused(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PauseOtherPlayers)
}

::google::protobuf::uint8* PauseOtherPlayers::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PauseOtherPlayers)
  // required bool paused = 1;
  if (has_paused()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->paused(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PauseOtherPlayers)
  return target;
}

int PauseOtherPlayers::ByteSize() const {
  int total_size = 0;

  // required bool paused = 1;
  if (has_paused()) {
    total_size += 1 + 1;
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PauseOtherPlayers::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const PauseOtherPlayers* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PauseOtherPlayers*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PauseOtherPlayers::MergeFrom(const PauseOtherPlayers& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_paused()) {
      set_paused(from.paused());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void PauseOtherPlayers::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PauseOtherPlayers::CopyFrom(const PauseOtherPlayers& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PauseOtherPlayers::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void PauseOtherPlayers::Swap(PauseOtherPlayers* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PauseOtherPlayers::InternalSwap(PauseOtherPlayers* other) {
  std::swap(paused_, other->paused_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PauseOtherPlayers::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PauseOtherPlayers_descriptor_;
  metadata.reflection = PauseOtherPlayers_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
