// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerIsCreated.proto

#ifndef PROTOBUF_PlayerIsCreated_2eproto__INCLUDED
#define PROTOBUF_PlayerIsCreated_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_PlayerIsCreated_2eproto();
void protobuf_AssignDesc_PlayerIsCreated_2eproto();
void protobuf_ShutdownFile_PlayerIsCreated_2eproto();

class PlayerIsCreated;

// ===================================================================

class PlayerIsCreated : public ::google::protobuf::Message {
 public:
  PlayerIsCreated();
  virtual ~PlayerIsCreated();

  PlayerIsCreated(const PlayerIsCreated& from);

  inline PlayerIsCreated& operator=(const PlayerIsCreated& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerIsCreated& default_instance();

  void Swap(PlayerIsCreated* other);

  // implements Message ----------------------------------------------

  inline PlayerIsCreated* New() const { return New(NULL); }

  PlayerIsCreated* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerIsCreated& from);
  void MergeFrom(const PlayerIsCreated& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PlayerIsCreated* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool Player = 1;
  inline bool has_player() const;
  inline void clear_player();
  static const int kPlayerFieldNumber = 1;
  inline bool player() const;
  inline void set_player(bool value);

  // @@protoc_insertion_point(class_scope:PlayerIsCreated)
 private:
  inline void set_has_player();
  inline void clear_has_player();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  bool player_;
  friend void  protobuf_AddDesc_PlayerIsCreated_2eproto();
  friend void protobuf_AssignDesc_PlayerIsCreated_2eproto();
  friend void protobuf_ShutdownFile_PlayerIsCreated_2eproto();

  void InitAsDefaultInstance();
  static PlayerIsCreated* default_instance_;
};
// ===================================================================


// ===================================================================

// PlayerIsCreated

// required bool Player = 1;
inline bool PlayerIsCreated::has_player() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerIsCreated::set_has_player() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerIsCreated::clear_has_player() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerIsCreated::clear_player() {
  player_ = false;
  clear_has_player();
}
inline bool PlayerIsCreated::player() const {
  // @@protoc_insertion_point(field_get:PlayerIsCreated.Player)
  return player_;
}
inline void PlayerIsCreated::set_player(bool value) {
  set_has_player();
  player_ = value;
  // @@protoc_insertion_point(field_set:PlayerIsCreated.Player)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PlayerIsCreated_2eproto__INCLUDED
