// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SelectMap.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SelectMap.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* SelectMap_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SelectMap_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_SelectMap_2eproto() {
  protobuf_AddDesc_SelectMap_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SelectMap.proto");
  GOOGLE_CHECK(file != NULL);
  SelectMap_descriptor_ = file->message_type(0);
  static const int SelectMap_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectMap, numofmap_),
  };
  SelectMap_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SelectMap_descriptor_,
      SelectMap::default_instance_,
      SelectMap_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectMap, _has_bits_[0]),
      -1,
      -1,
      sizeof(SelectMap),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectMap, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SelectMap_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SelectMap_descriptor_, &SelectMap::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SelectMap_2eproto() {
  delete SelectMap::default_instance_;
  delete SelectMap_reflection_;
}

void protobuf_AddDesc_SelectMap_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017SelectMap.proto\"\035\n\tSelectMap\022\020\n\010numOfM"
    "ap\030\001 \002(\005", 48);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SelectMap.proto", &protobuf_RegisterTypes);
  SelectMap::default_instance_ = new SelectMap();
  SelectMap::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SelectMap_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SelectMap_2eproto {
  StaticDescriptorInitializer_SelectMap_2eproto() {
    protobuf_AddDesc_SelectMap_2eproto();
  }
} static_descriptor_initializer_SelectMap_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int SelectMap::kNumOfMapFieldNumber;
#endif  // !_MSC_VER

SelectMap::SelectMap()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:SelectMap)
}

void SelectMap::InitAsDefaultInstance() {
}

SelectMap::SelectMap(const SelectMap& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SelectMap)
}

void SelectMap::SharedCtor() {
  _cached_size_ = 0;
  numofmap_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SelectMap::~SelectMap() {
  // @@protoc_insertion_point(destructor:SelectMap)
  SharedDtor();
}

void SelectMap::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SelectMap::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SelectMap::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SelectMap_descriptor_;
}

const SelectMap& SelectMap::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SelectMap_2eproto();
  return *default_instance_;
}

SelectMap* SelectMap::default_instance_ = NULL;

SelectMap* SelectMap::New(::google::protobuf::Arena* arena) const {
  SelectMap* n = new SelectMap;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SelectMap::Clear() {
  numofmap_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool SelectMap::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SelectMap)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 numOfMap = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &numofmap_)));
          set_has_numofmap();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SelectMap)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SelectMap)
  return false;
#undef DO_
}

void SelectMap::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SelectMap)
  // required int32 numOfMap = 1;
  if (has_numofmap()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->numofmap(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:SelectMap)
}

::google::protobuf::uint8* SelectMap::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SelectMap)
  // required int32 numOfMap = 1;
  if (has_numofmap()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->numofmap(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SelectMap)
  return target;
}

int SelectMap::ByteSize() const {
  int total_size = 0;

  // required int32 numOfMap = 1;
  if (has_numofmap()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->numofmap());
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SelectMap::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SelectMap* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SelectMap*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SelectMap::MergeFrom(const SelectMap& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_numofmap()) {
      set_numofmap(from.numofmap());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void SelectMap::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SelectMap::CopyFrom(const SelectMap& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SelectMap::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void SelectMap::Swap(SelectMap* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SelectMap::InternalSwap(SelectMap* other) {
  std::swap(numofmap_, other->numofmap_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SelectMap::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SelectMap_descriptor_;
  metadata.reflection = SelectMap_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
