// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Stop.proto

#ifndef PROTOBUF_Stop_2eproto__INCLUDED
#define PROTOBUF_Stop_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Stop_2eproto();
void protobuf_AssignDesc_Stop_2eproto();
void protobuf_ShutdownFile_Stop_2eproto();

class Close;

// ===================================================================

class Close : public ::google::protobuf::Message {
 public:
  Close();
  virtual ~Close();

  Close(const Close& from);

  inline Close& operator=(const Close& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Close& default_instance();

  void Swap(Close* other);

  // implements Message ----------------------------------------------

  inline Close* New() const { return New(NULL); }

  Close* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Close& from);
  void MergeFrom(const Close& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Close* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool Close = 1;
  inline bool has_close() const;
  inline void clear_close();
  static const int kCloseFieldNumber = 1;
  inline bool close() const;
  inline void set_close(bool value);

  // @@protoc_insertion_point(class_scope:Close)
 private:
  inline void set_has_close();
  inline void clear_has_close();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  bool close_;
  friend void  protobuf_AddDesc_Stop_2eproto();
  friend void protobuf_AssignDesc_Stop_2eproto();
  friend void protobuf_ShutdownFile_Stop_2eproto();

  void InitAsDefaultInstance();
  static Close* default_instance_;
};
// ===================================================================


// ===================================================================

// Close

// required bool Close = 1;
inline bool Close::has_close() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Close::set_has_close() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Close::clear_has_close() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Close::clear_close() {
  close_ = false;
  clear_has_close();
}
inline bool Close::close() const {
  // @@protoc_insertion_point(field_get:Close.Close)
  return close_;
}
inline void Close::set_close(bool value) {
  set_has_close();
  close_ = value;
  // @@protoc_insertion_point(field_set:Close.Close)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Stop_2eproto__INCLUDED
